Update 2024-03
mozsearch/ipdl_parser pull request #15
Opened 2024-03-20 23:08 UTC by selenography

Update the IPDL parser to handle various changes made to the language over the past several months.

_N.B.:_ I'm not sure if any downstream tooling is expecting `impl Display for Location` to be space-separated, so  40165b4c0b3a778ab164f2acdf82c4190c511c6c may need to be excluded. Nothing herein is dependent on it.

2024-03-20 23:13 UTC, selenography commented
Apologies; I've just realized that this needs additional tests written (and the current tests need to be adjusted).

2024-03-21 00:12 UTC, selenography commented
Never mind -- `cargo test` doesn't pass on master anyway! 🙃

I've included a few fixes that improve the situation, but updating and fixing all the tests is a little more work than I'm prepared to do at the moment — this was just a "while I'm waiting for other things to compile" project.

2024-03-21 15:38 UTC, amccreight requested changes
Like I mentioned in the IPC channel, it looks like the right fix here is to delete the entire check. https://hg.mozilla.org/mozilla-central/rev/bdcde8c620b43cde3941617f816a05cd2e6b716d

2024-03-21 17:46 UTC, amccreight commented on src/type_check.rs
> +            IPDLType::ImportedCxxType(_, Lifetime::RefCounted, _, _) => (),
(Note: this came from bug 1607634, unlike the rest of the patch which came from bug 1812156)

2024-03-24 15:34 UTC, amccreight commented on tests/smoke_test.rs
> +                        if !actual_error.find(&expected_error).is_some() {
Ok, I implemented lexer error translation locally. Thanks for bringing this up.

2024-03-24 18:20 UTC, amccreight commented
I moved most of this pull request, with some modifications, into a new pull request. The last patch is still missing, but hopefully get a chance to look that over soon. The new one is here: https://github.com/mozsearch/ipdl_parser/pull/16

2024-03-24 18:20 UTC, amccreight commented on src/type_check.rs
> +            IPDLType::ImportedCxxType(_, Lifetime::RefCounted, _, _) => (),
In my pull request, I split this change out into a separate diff, and implemented the rest of bug 1812156.

2024-03-25 22:38 UTC, amccreight commented
I've now landed all of the patches here (or rewritten them). cargo check should pass now. Thanks for your contributions!

2024-03-25 22:38 UTC, closed without merging